services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    links:
      - backend
    secrets:
      - certificate.crt
      - certificate.key

  backend:
    image: ghcr.io/innolan/backend
    pull_policy: always
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      - PROD=true
  
  frontend:
    image: ghcr.io/innolan/frontend
    pull_policy: always
    ports:
      - "3000:3000"
    
secrets:
  certificate.crt:
    file: ./certs/certificate.crt
  certificate.key:
    file: ./certs/certificate.key
  
