services:
  nginx:
    image: nginx:latest
    ports:
      - "1234:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - backend
    links:
      - backend
    secrets:
      - certificate.crt
      - certificate.key

  backend:
    image: ghcr.io/innolan/backend
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    environment:
      - PROD=true
    
secrets:
  certificate.crt:
    file: ./certs/certificate.crt
  certificate.key:
    file: ./certs/certificate.key
  
