name: Docker Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: push-to-ghcr
        uses: macbre/push-to-ghcr@v14
        with:
          github_token: ${{ secrets.TOKEN }}
          image_name: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # `docker compose restart` wouldn't work since we need to teardown the entire setup
          script: |
            docker compose down
            docker compose up -d
